---
- path: XML_Util-1.3.0/package.xml
  type: BSD
  text: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<package packagerversion=\"1.9.4\"
    version=\"2.0\" xmlns=\"http://pear.php.net/dtd/package-2.0\" xmlns:tasks=\"http://pear.php.net/dtd/tasks-1.0\"
    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://pear.php.net/dtd/tasks-1.0
    \    http://pear.php.net/dtd/tasks-1.0.xsd     http://pear.php.net/dtd/package-2.0
    \    http://pear.php.net/dtd/package-2.0.xsd\">\n <name>XML_Util</name>\n <channel>pear.php.net</channel>\n
    <summary>XML utility class</summary>\n <description>Selection of methods that
    are often needed when working with XML documents.  Functionality includes creating
    of attribute lists from arrays, creation of tags, validation of XML names and
    more.</description>\n <lead>\n  <name>Chuck Burgess</name>\n  <user>ashnazg</user>\n
    \ <email>ashnazg@php.net</email>\n  <active>yes</active>\n </lead>\n <lead>\n
    \ <name>Stephan Schmidt</name>\n  <user>schst</user>\n  <email>schst@php-tools.net</email>\n
    \ <active>no</active>\n </lead>\n <helper>\n  <name>Davey Shafik</name>\n  <user>davey</user>\n
    \ <email>davey@php.net</email>\n  <active>no</active>\n </helper>\n <date>2015-02-27</date>\n
    <time>12:11:41</time>\n <version>\n  <release>1.3.0</release>\n  <api>1.3.0</api>\n
    </version>\n <stability>\n  <release>stable</release>\n  <api>stable</api>\n </stability>\n
    <license uri=\"http://opensource.org/licenses/bsd-license\">BSD License</license>\n
    <notes>\n* Set minimum PHP version to 5.3.0\n* Mark static methods with static
    keyword\n </notes>\n <contents>\n  <dir baseinstalldir=\"/\" name=\"/\">\n   <file
    baseinstalldir=\"/\" md5sum=\"af2746028ae4395f549855a5e444ada7\" name=\"examples/example.php\"
    role=\"doc\" />\n   <file baseinstalldir=\"/\" md5sum=\"b9e52f4aa372c4067c609f49c2285b8f\"
    name=\"examples/example2.php\" role=\"doc\" />\n   <file baseinstalldir=\"/\"
    md5sum=\"73088689d58b71cd4f86013c88b72216\" name=\"tests/testBasic_apiVersion.phpt\"
    role=\"test\" />\n   <file baseinstalldir=\"/\" md5sum=\"4b17c0df7fbfb1bb2f3f636ebd6c2cbd\"
    name=\"tests/testBasic_attributesToString.phpt\" role=\"test\" />\n   <file baseinstalldir=\"/\"
    md5sum=\"dc4202f1451bbeb62a5bc7d56a7c774c\" name=\"tests/testBasic_collapseEmptyTags.phpt\"
    role=\"test\" />\n   <file baseinstalldir=\"/\" md5sum=\"4c87fda94fdfb7a78ba84998d6e28f45\"
    name=\"tests/testBasic_createCDataSection.phpt\" role=\"test\" />\n   <file baseinstalldir=\"/\"
    md5sum=\"c101844768f146653c59c81978060158\" name=\"tests/testBasic_createComment.phpt\"
    role=\"test\" />\n   <file baseinstalldir=\"/\" md5sum=\"ba75d66c2f0fb0010c71f3bcd1f64eb2\"
    name=\"tests/testBasic_createEndElement.phpt\" role=\"test\" />\n   <file baseinstalldir=\"/\"
    md5sum=\"ad786fb687e1eea1f6890a7424709c79\" name=\"tests/testBasic_createStartElement.phpt\"
    role=\"test\" />\n   <file baseinstalldir=\"/\" md5sum=\"5f453edadebaa3435c8e6f09a3aaaa9c\"
    name=\"tests/testBasic_createTag.phpt\" role=\"test\" />\n   <file baseinstalldir=\"/\"
    md5sum=\"637fa86b8bcf0086334f69004a435169\" name=\"tests/testBasic_createTagFromArray.phpt\"
    role=\"test\" />\n   <file baseinstalldir=\"/\" md5sum=\"817882a0ab33e60f17ee71874ad975f0\"
    name=\"tests/testBasic_getDocTypeDeclaration.phpt\" role=\"test\" />\n   <file
    baseinstalldir=\"/\" md5sum=\"5bc1926a488a6b63ec6366bfcf06a50a\" name=\"tests/testBasic_getXmlDeclaration.phpt\"
    role=\"test\" />\n   <file baseinstalldir=\"/\" md5sum=\"a727860d55c14194fdaffa839a59a540\"
    name=\"tests/testBasic_isValidName.phpt\" role=\"test\" />\n   <file baseinstalldir=\"/\"
    md5sum=\"300a6192f7cc6f7bc3d8f2576b51e4b0\" name=\"tests/testBasic_raiseError.phpt\"
    role=\"test\" />\n   <file baseinstalldir=\"/\" md5sum=\"e6717d43001775cccd52bd5195cf02e0\"
    name=\"tests/testBasic_replaceEntities.phpt\" role=\"test\" />\n   <file baseinstalldir=\"/\"
    md5sum=\"431856aa83a23396a9f00915dd2be192\" name=\"tests/testBasic_reverseEntities.phpt\"
    role=\"test\" />\n   <file baseinstalldir=\"/\" md5sum=\"ab035534463cae8cc903e907aead8ffe\"
    name=\"tests/testBasic_splitQualifiedName.phpt\" role=\"test\" />\n   <file baseinstalldir=\"/\"
    md5sum=\"1850856692ff6c6df5e8acb16e1080ce\" name=\"tests/testBug_4950.phpt\" role=\"test\"
    />\n   <file baseinstalldir=\"/\" md5sum=\"b4127883df40a4b0d1736ad42215ee25\"
    name=\"tests/testBug_5392.phpt\" role=\"test\" />\n   <file baseinstalldir=\"/\"
    md5sum=\"b133427f8ea9b60c5bec7400cd5e4c7f\" name=\"tests/testBug_18343.phpt\"
    role=\"test\" />\n   <file baseinstalldir=\"/\" md5sum=\"b702b9cd014402420453c66ae7a96803\"
    name=\"XML/Util.php\" role=\"php\">\n    <tasks:replace from=\"@version@\" to=\"version\"
    type=\"package-info\" />\n   </file>\n  </dir>\n </contents>\n <dependencies>\n
    \ <required>\n   <php>\n    <min>5.3.0</min>\n   </php>\n   <pearinstaller>\n
    \   <min>1.4.3</min>\n   </pearinstaller>\n   <extension>\n    <name>pcre</name>\n
    \  </extension>\n  </required>\n </dependencies>\n <phprelease />\n <changelog>\n
    \ <release>\n   <version>\n    <release>0.1</release>\n    <api>0.1</api>\n   </version>\n
    \  <stability>\n    <release>stable</release>\n    <api>stable</api>\n   </stability>\n
    \  <date>2003-08-01</date>\n   <license uri=\"http://www.php.net/license\">PHP
    License</license>\n   <notes>\ninital release\n   </notes>\n  </release>\n  <release>\n
    \  <version>\n    <release>0.1.1</release>\n    <api>0.1.1</api>\n   </version>\n
    \  <stability>\n    <release>stable</release>\n    <api>stable</api>\n   </stability>\n
    \  <date>2003-08-02</date>\n   <license uri=\"http://www.php.net/license\">PHP
    License</license>\n   <notes>\nbugfix: removed bug in createTagFromArray\n   </notes>\n
    \ </release>\n  <release>\n   <version>\n    <release>0.2</release>\n    <api>0.2</api>\n
    \  </version>\n   <stability>\n    <release>stable</release>\n    <api>stable</api>\n
    \  </stability>\n   <date>2003-08-12</date>\n   <license uri=\"http://www.php.net/license\">PHP
    License</license>\n   <notes>\nadded XML_Util::getDocTypeDeclaration()\n   </notes>\n
    \ </release>\n  <release>\n   <version>\n    <release>0.2.1</release>\n    <api>0.2.1</api>\n
    \  </version>\n   <stability>\n    <release>stable</release>\n    <api>stable</api>\n
    \  </stability>\n   <date>2003-09-05</date>\n   <license uri=\"http://www.php.net/license\">PHP
    License</license>\n   <notes>\nfixed bug with zero as tag content in createTagFromArray
    and createTag\n   </notes>\n  </release>\n  <release>\n   <version>\n    <release>0.3</release>\n
    \   <api>0.3</api>\n   </version>\n   <stability>\n    <release>stable</release>\n
    \   <api>stable</api>\n   </stability>\n   <date>2003-09-12</date>\n   <license
    uri=\"http://www.php.net/license\">PHP License</license>\n   <notes>\nadded createStartElement()
    and createEndElement()\n   </notes>\n  </release>\n  <release>\n   <version>\n
    \   <release>0.4</release>\n    <api>0.4</api>\n   </version>\n   <stability>\n
    \   <release>stable</release>\n    <api>stable</api>\n   </stability>\n   <date>2003-09-21</date>\n
    \  <license uri=\"http://www.php.net/license\">PHP License</license>\n   <notes>\nadded
    createCDataSection(),\nadded support for CData sections in createTag* methods,\nfixed
    bug #23,\nfixed bug in splitQualifiedName()\n   </notes>\n  </release>\n  <release>\n
    \  <version>\n    <release>0.5</release>\n    <api>0.5</api>\n   </version>\n
    \  <stability>\n    <release>stable</release>\n    <api>stable</api>\n   </stability>\n
    \  <date>2003-09-23</date>\n   <license uri=\"http://www.php.net/license\">PHP
    License</license>\n   <notes>\nadded support for multiline attributes in attributesToString(),
    createTag*() and createStartElement (requested by Yavor Shahpasov for XML_Serializer),\nadded
    createComment\n   </notes>\n  </release>\n  <release>\n   <version>\n    <release>0.5.1</release>\n
    \   <api>0.5.1</api>\n   </version>\n   <stability>\n    <release>stable</release>\n
    \   <api>stable</api>\n   </stability>\n   <date>2003-09-26</date>\n   <license
    uri=\"http://www.php.net/license\">PHP License</license>\n   <notes>\nadded default
    namespace parameter (optional) in splitQualifiedName() (requested by Sebastian
    Bergmann)\n   </notes>\n  </release>\n  <release>\n   <version>\n    <release>0.5.2</release>\n
    \   <api>0.5.2</api>\n   </version>\n   <stability>\n    <release>stable</release>\n
    \   <api>stable</api>\n   </stability>\n   <date>2003-11-22</date>\n   <license
    uri=\"http://www.php.net/license\">PHP License</license>\n   <notes>\nnow creates
    XHTML compliant empty tags (Davey),\nminor whitespace fixes (Davey)\n   </notes>\n
    \ </release>\n  <release>\n   <version>\n    <release>0.6.0beta1</release>\n    <api>0.6.0beta1</api>\n
    \  </version>\n   <stability>\n    <release>beta</release>\n    <api>beta</api>\n
    \  </stability>\n   <date>2004-05-24</date>\n   <license uri=\"http://www.php.net/license\">PHP
    License</license>\n   <notes>\n- Fixed bug 1438 (namespaces not accepted for isValidName())
    (thanks to davey)\n- added optional parameter to replaceEntities() to define the
    set of entities to replace\n- added optional parameter to attributesToString()
    to define, whether entities should be replaced (requested by Sebastian Bergmann)\n-
    allowed second parameter to XML_Util::attributesToString() to be an array containing
    options (easier to use, if you only need to set the last parameter)\n- introduced
    XML_Util::raiseError() to avoid the necessity of including PEAR.php, will only
    be included on error\n   </notes>\n  </release>\n  <release>\n   <version>\n    <release>0.6.0</release>\n
    \   <api>0.6.0</api>\n   </version>\n   <stability>\n    <release>stable</release>\n
    \   <api>stable</api>\n   </stability>\n   <date>2004-06-07</date>\n   <license
    uri=\"http://www.php.net/license\">PHP License</license>\n   <notes>\n- Fixed
    bug 1438 (namespaces not accepted for isValidName()) (thanks to davey)\n- added
    optional parameter to replaceEntities() to define the set of entities to replace\n-
    added optional parameter to attributesToString() to define, whether entities should
    be replaced (requested by Sebastian Bergmann)\n- allowed second parameter to XML_Util::attributesToString()
    to be an array containing options (easier to use, if you only need to set the
    last parameter)\n- introduced XML_Util::raiseError() to avoid the necessity of
    including PEAR.php, will only be included on error\n   </notes>\n  </release>\n
    \ <release>\n   <version>\n    <release>0.6.1</release>\n    <api>0.6.1</api>\n
    \  </version>\n   <stability>\n    <release>stable</release>\n    <api>stable</api>\n
    \  </stability>\n   <date>2004-10-28</date>\n   <license uri=\"http://www.php.net/license\">PHP
    License</license>\n   <notes>\n- Added check for tag name (either as local part
    or qualified name) in createTagFromArray() (bug #1083)\n   </notes>\n  </release>\n
    \ <release>\n   <version>\n    <release>1.0.0</release>\n    <api>1.0.0</api>\n
    \  </version>\n   <stability>\n    <release>stable</release>\n    <api>stable</api>\n
    \  </stability>\n   <date>2004-10-28</date>\n   <license uri=\"http://www.php.net/license\">PHP
    License</license>\n   <notes>\n- Added reverseEntities() (request #2639)\n   </notes>\n
    \ </release>\n  <release>\n   <version>\n    <release>1.1.0</release>\n    <api>1.1.0</api>\n
    \  </version>\n   <stability>\n    <release>stable</release>\n    <api>stable</api>\n
    \  </stability>\n   <date>2004-11-19</date>\n   <license uri=\"http://www.php.net/license\">PHP
    License</license>\n   <notes>\n- Added collapseEmptyTags (patch by Sebastian Bergmann
    and Thomas Duffey)\n   </notes>\n  </release>\n  <release>\n   <version>\n    <release>1.1.1</release>\n
    \   <api>1.1.1</api>\n   </version>\n   <stability>\n    <release>stable</release>\n
    \   <api>stable</api>\n   </stability>\n   <date>2004-12-23</date>\n   <license
    uri=\"http://www.php.net/license\">PHP License</license>\n   <notes>\n- fixed
    bug in replaceEntities() and reverseEntities() in conjunction with XML_UTIL_ENTITIES_HTML\n-
    createTag() and createTagFromArray() now accept XML_UTIL_ENTITIES_XML, XML_UTIL_ENTITIES_XML_REQUIRED,
    XML_UTIL_ENTITIES_HTML, XML_UTIL_ENTITIES_NONE and XML_UTIL_CDATA_SECTION as $replaceEntities
    parameter\n   </notes>\n  </release>\n  <release>\n   <version>\n    <release>1.1.2</release>\n
    \   <api>1.1.2</api>\n   </version>\n   <stability>\n    <release>stable</release>\n
    \   <api>stable</api>\n   </stability>\n   <date>2006-12-01</date>\n   <license
    uri=\"http://www.php.net/license\">PHP License</license>\n   <notes>\n- fixed
    bug #5419: isValidName() now checks for character classes\n- implemented request
    #8196: added optional parameter to influence array sorting to createTag() createTagFromArray()
    and createStartElement()\n   </notes>\n  </release>\n  <release>\n   <version>\n
    \   <release>1.1.4</release>\n    <api>1.1.4</api>\n   </version>\n   <stability>\n
    \   <release>stable</release>\n    <api>stable</api>\n   </stability>\n   <date>2006-12-16</date>\n
    \  <license uri=\"http://www.php.net/license\">PHP License</license>\n   <notes>\n-
    Fixed bug #9561: Not allowing underscores in middle of tags\n   </notes>\n  </release>\n
    \ <release>\n   <version>\n    <release>1.2.0a1</release>\n    <api>1.2.0</api>\n
    \  </version>\n   <stability>\n    <release>alpha</release>\n    <api>alpha</api>\n
    \  </stability>\n   <date>2008-05-04</date>\n   <license uri=\"http://opensource.org/licenses/bsd-license\">BSD
    License</license>\n   <notes>\nChanged license to New BSD License (Req #13826
    [ashnazg])\nAdded a test suite against all API methods [ashnazg]\nSwitch to package.xml
    v2 [ashnazg]\nFixed Bug #4950: Incorrect CDATA serializing [ashnazg|ja.doma]\n
    \  </notes>\n  </release>\n  <release>\n   <version>\n    <release>1.2.0a2</release>\n
    \   <api>1.2.0</api>\n   </version>\n   <stability>\n    <release>alpha</release>\n
    \   <api>alpha</api>\n   </stability>\n   <date>2008-05-22</date>\n   <license
    uri=\"http://opensource.org/licenses/bsd-license\">BSD License</license>\n   <notes>\nChanged
    license to New BSD License (Req #13826 [ashnazg])\nAdded a test suite against
    all API methods [ashnazg]\nSwitch to package.xml v2 [ashnazg]\nAdded Req #13839:
    Missing XHTML empty tags to collapse [ashnazg|drry]\nFixed Bug #5392: encoding
    of ISO-8859-1 is the only supported encoding [ashnazg]\nFixed Bug #4950: Incorrect
    CDATA serializing [ashnazg|drry]\n-- (this fix differs from the one in v1.2.0a1)\n
    \  </notes>\n  </release>\n  <release>\n   <version>\n    <release>1.2.0RC1</release>\n
    \   <api>1.2.0</api>\n   </version>\n   <stability>\n    <release>beta</release>\n
    \   <api>beta</api>\n   </stability>\n   <date>2008-07-12</date>\n   <license
    uri=\"http://opensource.org/licenses/bsd-license\">BSD License</license>\n   <notes>\nChanged
    license to New BSD License (Req #13826 [ashnazg])\nAdded a test suite against
    all API methods [ashnazg]\nSwitch to package.xml v2 [ashnazg]\nAdded Req #13839:
    Missing XHTML empty tags to collapse [ashnazg|drry]\nFixed Bug #5392: encoding
    of ISO-8859-1 is the only supported encoding [ashnazg]\nFixed Bug #4950: Incorrect
    CDATA serializing [ashnazg|drry]\n-- (this fix differs from the one in v1.2.0a1)\n
    \  </notes>\n  </release>\n  <release>\n   <version>\n    <release>1.2.0</release>\n
    \   <api>1.2.0</api>\n   </version>\n   <stability>\n    <release>stable</release>\n
    \   <api>stable</api>\n   </stability>\n   <date>2008-07-26</date>\n   <license
    uri=\"http://opensource.org/licenses/bsd-license\">BSD License</license>\n   <notes>\nChanged
    license to New BSD License (Req #13826 [ashnazg])\nAdded a test suite against
    all API methods [ashnazg]\nSwitch to package.xml v2 [ashnazg]\nAdded Req #13839:
    Missing XHTML empty tags to collapse [ashnazg|drry]\nFixed Bug #5392: encoding
    of ISO-8859-1 is the only supported encoding [ashnazg]\nFixed Bug #4950: Incorrect
    CDATA serializing [ashnazg|drry]\n-- (this fix differs from the one in v1.2.0a1)\n
    \  </notes>\n  </release>\n  <release>\n   <version>\n    <release>1.2.1</release>\n
    \   <api>1.2.0</api>\n   </version>\n   <stability>\n    <release>stable</release>\n
    \   <api>stable</api>\n   </stability>\n   <date>2011-12-31</date>\n   <license
    uri=\"http://opensource.org/licenses/bsd-license\">BSD License</license>\n   <notes>\nFixed
    Bug #14760: Bug in getDocTypeDeclaration() [ashnazg|fpospisil]\n   </notes>\n
    \ </release>\n  <release>\n   <version>\n    <release>1.2.2</release>\n    <api>1.2.0</api>\n
    \  </version>\n   <stability>\n    <release>stable</release>\n    <api>stable</api>\n
    \  </stability>\n   <date>2014-06-07</date>\n   <license uri=\"http://opensource.org/licenses/bsd-license\">BSD
    License</license>\n   <notes>\nQA release\n\nBug #18343 Entities in file names
    decoded during packaging\nBug #19174\tupgrade PHPUnit require statements &amp;
    other fixes (for PEAR QA Team)\nRequest #19750\texamples/example.php encoding\n
    \  </notes>\n  </release>\n  <release>\n   <version>\n    <release>1.2.3</release>\n
    \   <api>1.2.0</api>\n   </version>\n   <stability>\n    <release>stable</release>\n
    \   <api>stable</api>\n   </stability>\n   <date>2014-06-07</date>\n   <license
    uri=\"http://opensource.org/licenses/bsd-license\">BSD License</license>\n   <notes>\nBug
    #20293\tBroken installation for 1.2.2\n   </notes>\n  </release>\n  <release>\n
    \  <version>\n    <release>1.3.0</release>\n    <api>1.3.0</api>\n   </version>\n
    \  <stability>\n    <release>stable</release>\n    <api>stable</api>\n   </stability>\n
    \  <date>2015-02-27</date>\n   <license uri=\"http://opensource.org/licenses/bsd-license\">BSD
    License</license>\n   <notes>\n* Set minimum PHP version to 5.3.0\n* Mark static
    methods with static keyword\n   </notes>\n  </release>\n </changelog>\n</package>\n"
