---
- path: tidy-html5-5.0.0/LICENSE.txt
  type: W3C
  text: "\n  Copyright (c) 1998-2015 World Wide Web Consortium\n  (Massachusetts Institute
    of Technology, European Research \n  Consortium for Informatics and Mathematics,
    Keio University).\n  All Rights Reserved.\n\n  Contributing Author(s):\n\n     Dave
    Raggett <dsr@w3.org>\n\n  The contributing author(s) would like to thank all those
    who\n  helped with testing, bug fixes and suggestions for improvements. \n  This
    wouldn't have been possible without your help.\n\n  COPYRIGHT NOTICE:\n \n  This
    software and documentation is provided \"as is,\" and\n  the copyright holders
    and contributing author(s) make no\n  representations or warranties, express or
    implied, including\n  but not limited to, warranties of merchantability or fitness\n
    \ for any particular purpose or that the use of the software or\n  documentation
    will not infringe any third party patents,\n  copyrights, trademarks or other
    rights. \n\n  The copyright holders and contributing author(s) will not be held\n
    \ liable for any direct, indirect, special or consequential damages\n  arising
    out of any use of the software or documentation, even if\n  advised of the possibility
    of such damage.\n\n  Permission is hereby granted to use, copy, modify, and distribute\n
    \ this source code, or portions hereof, documentation and executables,\n  for
    any purpose, without fee, subject to the following restrictions:\n\n  1. The origin
    of this source code must not be misrepresented.\n  2. Altered versions must be
    plainly marked as such and must\n     not be misrepresented as being the original
    source.\n  3. This Copyright notice may not be removed or altered from any\n     source
    or altered source distribution.\n \n  The copyright holders and contributing author(s)
    specifically\n  permit, without fee, and encourage the use of this source code\n
    \ as a component for supporting the Hypertext Markup Language in\n  commercial
    products. If you use this source code in a product,\n  acknowledgment is not required
    but would be appreciated.\n\n"
