---
- path: glew-2.0.0/LICENSE.txt
  type: BSD-3-Clause
  text: "The OpenGL Extension Wrangler Library\nCopyright (C) 2002-2007, Milan Ikits
    <milan ikits[]ieee org>\nCopyright (C) 2002-2007, Marcelo E. Magallon <mmagallo[]debian
    org>\nCopyright (C) 2002, Lev Povalahev\nAll rights reserved.\n\nRedistribution
    and use in source and binary forms, with or without \nmodification, are permitted
    provided that the following conditions are met:\n\n* Redistributions of source
    code must retain the above copyright notice, \n  this list of conditions and the
    following disclaimer.\n* Redistributions in binary form must reproduce the above
    copyright notice, \n  this list of conditions and the following disclaimer in
    the documentation \n  and/or other materials provided with the distribution.\n*
    The name of the author may be used to endorse or promote products \n  derived
    from this software without specific prior written permission.\n\nTHIS SOFTWARE
    IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" \nAND ANY EXPRESS
    OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE \nIMPLIED WARRANTIES
    OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\nARE DISCLAIMED. IN NO
    EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE \nLIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR \nCONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
    LIMITED TO, PROCUREMENT OF \nSUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
    OR PROFITS; OR BUSINESS\nINTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
    WHETHER IN\nCONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\nARISING
    IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF\nTHE POSSIBILITY
    OF SUCH DAMAGE.\n\n\nMesa 3-D graphics library\nVersion:  7.0\n\nCopyright (C)
    1999-2007  Brian Paul   All Rights Reserved.\n\nPermission is hereby granted,
    free of charge, to any person obtaining a\ncopy of this software and associated
    documentation files (the \"Software\"),\nto deal in the Software without restriction,
    including without limitation\nthe rights to use, copy, modify, merge, publish,
    distribute, sublicense,\nand/or sell copies of the Software, and to permit persons
    to whom the\nSoftware is furnished to do so, subject to the following conditions:\n\nThe
    above copyright notice and this permission notice shall be included\nin all copies
    or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\",
    WITHOUT WARRANTY OF ANY KIND, EXPRESS\nOR IMPLIED, INCLUDING BUT NOT LIMITED TO
    THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
    \ IN NO EVENT SHALL\nBRIAN PAUL BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
    WHETHER IN\nAN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
    IN\nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\n\nCopyright
    (c) 2007 The Khronos Group Inc.\n\nPermission is hereby granted, free of charge,
    to any person obtaining a\ncopy of this software and/or associated documentation
    files (the\n\"Materials\"), to deal in the Materials without restriction, including\nwithout
    limitation the rights to use, copy, modify, merge, publish,\ndistribute, sublicense,
    and/or sell copies of the Materials, and to\npermit persons to whom the Materials
    are furnished to do so, subject to\nthe following conditions:\n\nThe above copyright
    notice and this permission notice shall be included\nin all copies or substantial
    portions of the Materials.\n\nTHE MATERIALS ARE PROVIDED \"AS IS\", WITHOUT WARRANTY
    OF ANY KIND,\nEXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
    OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\nIN
    NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY\nCLAIM, DAMAGES
    OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,\nTORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE\nMATERIALS OR THE USE OR OTHER DEALINGS
    IN THE MATERIALS.\n"
