---
- path: pkcs11-helper-1.22/COPYING
  type: GPL-2.0,OpenSSL
  text: "\npkcs11-helper License\n\n\tCopyright (c) 2005-2011 Alon Bar-Lev <alon.barlev@gmail.com>\n\tAll
    rights reserved.\n\n\tThis software is available to you under a choice of one
    of two\n\tlicenses.  You may choose to be licensed under the terms of the GNU\n\tGeneral
    Public License (GPL) Version 2, or the BSD license.\n\n\tGNU General Public License
    (GPL) Version 2\n\t===========================================\n\tThis program
    is free software; you can redistribute it and/or modify\n\tit under the terms
    of the GNU General Public License version 2\n\tas published by the Free Software
    Foundation.\n\n\tThis program is distributed in the hope that it will be useful,\n\tbut
    WITHOUT ANY WARRANTY; without even the implied warranty of\n\tMERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE.  See the\n\tGNU General Public License for
    more details.\n\n\tYou should have received a copy of the GNU General Public License\n\talong
    with this program (see the file COPYING.GPL included with this\n\tdistribution);
    if not, write to the Free Software Foundation, Inc.,\n\t51 Franklin Street, Fifth
    Floor, Boston, MA 02110-1301 USA.\n\n\tBSD License\n\t============\n\tRedistribution
    and use in source and binary forms, with or without\n\tmodification, are permitted
    provided that the following conditions are met:\n\n\t    o Redistributions of
    source code must retain the above copyright notice,\n\t      this list of conditions
    and the following disclaimer.\n\t    o Redistributions in binary form must reproduce
    the above copyright\n\t      notice, this list of conditions and the following
    disclaimer in the\n\t      documentation and/or other materials provided with
    the distribution.\n\t    o Neither the name of the Alon Bar-Lev nor the names
    of its\n\t      contributors may be used to endorse or promote products derived
    from\n\t      this software without specific prior written permission.\n\n\tTHIS
    SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"\n\tAND
    ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n\tIMPLIED
    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\n\tARE DISCLAIMED.
    IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE\n\tLIABLE FOR ANY DIRECT,
    INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR\n\tCONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF\n\tSUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
    DATA, OR PROFITS; OR BUSINESS\n\tINTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
    OF LIABILITY, WHETHER IN\n\tCONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
    OR OTHERWISE)\n\tARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
    OF THE\n\tPOSSIBILITY OF SUCH DAMAGE.\n\nPackeging License\n\n\tRPM\n\t\tCopyright
    (c) 2006-2007 Eddy Nigg\n\n\tDebian\n\t\tCopyright (c) 2007 Sandro Wefel\n\nm4
    Macros License\n\n\tautoconf/automake\n\t\tCopyright (C) 2002, 2003 Free Software
    Foundation, Inc.\n\n\tpkg.m4\n\t\tCopyright © 2004 Scott James Remnant <scott@netsplit.com>.\n\t\n\tAX_CPP_VARARG*\n\t\tCopyright
    (c) James Yonan <jim@yonan.net>\n\t\tCopyright (c) Matthias Andree <matthias.andree@web.de>\n\npkcs11.h
    License\n\tCopyright 2006, 2007 g10 Code GmbH\n\tCopyright 2006 Andreas Jellinghaus\n\nOpenSSL
    License (Optional component, parsing certificates, engine)\n\n\tThis product includes
    software developed by the OpenSSL Project\n\tfor use in the OpenSSL Toolkit (http://www.OpenSSL.org/)\n\n\tThis
    product includes cryptographic software written by Eric Young\n\t(eay@cryptsoft.com).
    \ This product includes software written by Tim\n\tHudson (tjh@cryptsoft.com).\n\nGnuTLS
    License (Optional component, for a complete GPLed license, replaces OpenSSL)\n\n\tCopyright
    (C) 2000, 2001, 2002, 2003, 2004, 2005 Nikos Mavroyanopoulos\n\tSee the end for
    copying conditions.\n\n\tThe copyright holder for Gnutls is Free Software Foundation,\n\tInc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,\n\tUSA.\n\nNSS License
    (Optional component, parsing certificates, engine)\n\n\tThe Original Code is Mozilla
    Communicator client code, released\n\tMarch 31, 1998.\n\n\tThe Initial Developer
    of the Original Code is Netscape\n\tCommunications Corporation. Portions created
    by Netscape are\n\tCopyright (C) 1998-1999 Netscape Communications Corporation.
    All\n\tRights Reserved.\n\nDoxygen License (Optional component, documentation)\n\n\tCopyright
    © 1997-2006 by Dimitri van Heesch.\n\n\tPermission to use, copy, modify, and distribute
    this software and\n\tits documentation under the terms of the GNU General Public
    License\n\tis hereby granted. No representations are made about the suitability\n\tof
    this software for any purpose. It is provided \"as is\" without express\n\tor
    implied warranty. See the GNU General Public License for more details. \n\n\tDocuments
    produced by doxygen are derivative works derived\n\tfrom the input used in their
    production; they are not affected by this\n\tlicense.\n"
