---
- path: byacc-20150711/README
  type: Public-domain
  text: "-- $Id: README,v 1.2 2004/03/28 17:24:53 tom Exp $\n\nThe original README
    is below.  I've updated this version of Berkeley Yacc\nto make it ANSI C compliant
    - Thomas Dickey\n\n-------------------------------------------------------------------------------\n
    \   Berkeley Yacc is an LALR(1) parser generator.  Berkeley Yacc has been made\nas
    compatible as possible with AT&T Yacc.  Berkeley Yacc can accept any input\nspecification
    that conforms to the AT&T Yacc documentation.  Specifications\nthat take advantage
    of undocumented features of AT&T Yacc will probably be\nrejected.\n\n    Berkeley
    Yacc is distributed with no warranty whatever.  The code is certain\nto contain
    errors.  Neither the author nor any contributor takes responsibility\nfor any
    consequences of its use.\n\n    Berkeley Yacc is in the public domain.  The data
    structures and algorithms\nused in Berkeley Yacc are all either taken from documents
    available to the\ngeneral public or are inventions of the author.  Anyone may
    freely distribute\nsource or binary forms of Berkeley Yacc whether unchanged or
    modified.\nDistributers may charge whatever fees they can obtain for Berkeley
    Yacc.\nPrograms generated by Berkeley Yacc may be distributed freely.\n\n    Please
    report bugs to\n\n\t\t\trobert.corbett@eng.Sun.COM\n\nInclude a small example
    if possible.  Please include the banner string from\nskeleton.c with the bug report.
    \ Do not expect rapid responses.\n"
