name: Jetware
motto: !ruby/object:StringML
  en: autonomous software systems
  ru: автономные программные системы
  it: ambienti operativi personalizzati per le applicazioni web 
copyright: '&copy; 2016&mdash;2018 <a href=/contacts>Jetware team</a>'
