---
- path: less-487/LICENSE
  type: BSD-style
  text: "                          Less License\n                          ------------\n\nLess\nCopyright
    (C) 1984-2016  Mark Nudelman\n\nRedistribution and use in source and binary forms,
    with or without\nmodification, are permitted provided that the following conditions\nare
    met:\n1. Redistributions of source code must retain the above copyright\n   notice,
    this list of conditions and the following disclaimer.\n2. Redistributions in binary
    form must reproduce the above copyright\n   notice in the documentation and/or
    other materials provided with \n   the distribution.\n\nTHIS SOFTWARE IS PROVIDED
    BY THE AUTHOR ``AS IS'' AND ANY\nEXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
    NOT LIMITED TO, THE\nIMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
    \nPURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE\nFOR ANY DIRECT,
    INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR \nCONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT \nOF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
    DATA, OR PROFITS; OR \nBUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
    OF LIABILITY, \nWHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
    \nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN \nIF
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\n"
